# This is a default, demo config used by our testing.

[sources.heroku]
  type = "logplex"
  address = "0.0.0.0:${PORT}"

#[sinks.my_sink_id]
#  type = "http"
#  inputs = ["heroku"]
#  uri = "https://somewhere:9000/endpoint" # required