# This is a default, demo config used by our testing.

[sources.heroku]
  type = "logplex"
  address = "0.0.0.0:${PORT}"
  auth.username = "${LOGPLEX_AUTH_USERNAME}"
  auth.password = "${LOGPLEX_AUTH_PASSWORD}"
  
[sinks.replace_me]
 type = "blackhole"
 inputs = ["heroku"]
 print_amount = 1000